version: 2.1

jobs:
  sonarqube_scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # Use SonarQube's official scanner image
    steps:
      - checkout  # Check out the code from your GitHub repository
      - run:
          name: "Run SonarQube Scan"
          command: |
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url="$SONAR_HOST_URL" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.sources="employee-payments-portal" \
              -Dsonar.branch.name="${CIRCLE_BRANCH}" \
              -Dsonar.exclusions="**/*.c,**/*.cpp,**/*.h,**/tests/**" \
              -Dsonar.c.file.suffixes=- \
              -Dsonar.cpp.file.suffixes=- \
              -Dsonar.objc.file.suffixes=-

workflows:
  version: 2
  scan_pipeline:
    jobs:
      - sonarqube_scan
