version: 2.1

jobs:
  setup:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Install Root Dependencies"
          command: npm install

  test-client:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Clean Install Client Dependencies"
          command: npm ci --prefix employee-payments-portal/client
      - run:
          name: "Set Execute Permissions for Node Modules"
          command: chmod -R +x employee-payments-portal/client/node_modules/.bin
      - run:
          name: "Run Client Tests"
          command: npm test --prefix employee-payments-portal/client

  test-server:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Install Server Dependencies"
          command: npm ci --prefix employee-payments-portal/server
      - run:
          name: "Run Server Tests"
          command: npm test --prefix employee-payments-portal/server

workflows:
  version: 2
  test:
    jobs:
      - setup
      - test-client:
          requires:
            - setup
      - test-server:
          requires:
            - setup
