version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Install Backend Dependencies"
          command: |
            npm install --prefix employee-payments-portal/server
      - run:
          name: "Install Client Dependencies"
          command: |
            npm install --prefix employee-payments-portal/client
      - run:
          name: "Build Backend Application"
          command: |
            npm run build --prefix employee-payments-portal/server
      - run:
          name: "Build Client Application"
          command: |
            npm run build --prefix employee-payments-portal/client

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Install Backend Dependencies"
          command: |
            npm install --prefix employee-payments-portal/server
      - run:
          name: "Install Client Dependencies"
          command: |
            npm install --prefix employee-payments-portal/client
      - run:
          name: "Run Backend Tests"
          command: |
            npm test --prefix employee-payments-portal/server
      - run:
          name: "Run Client Tests"
          command: |
            npm test --prefix employee-payments-portal/client

  sonarqube_scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: "Run SonarQube Scan"
          command: |
            cd employee-payments-portal && sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url="$SONAR_HOST_URL" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.sources="client,server" \
              -Dsonar.branch.name="${CIRCLE_BRANCH}" \
              -Dsonar.exclusions="**/*.c,**/*.cpp,**/*.h,**/tests/**" \
              -Dsonar.c.file.suffixes=- \
              -Dsonar.cpp.file.suffixes=- \
              -Dsonar.objc.file.suffixes=-

workflows:
  version: 2
  devsecops_pipeline:
    jobs:
      - build
      - test
      - sonarqube_scan:
          requires:
            - test
          filters:
            branches:
              only:
                - main
