version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Install Dependencies for Client and Server"
          command: |
            npm install --prefix employee-payments-portal/client
            npm install --prefix employee-payments-portal/server

   test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Install Dependencies for Testing"
          command: |
            npm install --prefix employee-payments-portal/client
      - run:
          name: "Adjust Permissions for Testing"
          command: |
            chmod -R +x node_modules/.bin || true
      - run:
          name: "Run Client Tests"
          command: |
            npm test --prefix employee-payments-portal/client

  sonarqube_scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: "Run SonarQube Scan"
          command: |
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url="$SONAR_HOST_URL" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.sources="employee-payments-portal" \
              -Dsonar.branch.name="${CIRCLE_BRANCH}" \
              -Dsonar.exclusions="**/*.c,**/*.cpp,**/*.h,**/tests/**" \
              -Dsonar.c.file.suffixes=- \
              -Dsonar.cpp.file.suffixes=- \
              -Dsonar.objc.file.suffixes=-

workflows:
  version: 2
  devsecops_pipeline:
    jobs:
      - install_dependencies
      - test:
          requires:
            - install_dependencies
      - sonarqube_scan:
          requires:
            - test
