version: 2.1

jobs:
  build-server:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Install Server Dependencies"
          command: |
            npm install --prefix server
      - run:
          name: "Build Server"
          command: |
            npm run build --prefix server

  build-client:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Install Client Dependencies"
          command: |
            npm install --prefix client
      - run:
          name: "Build Client"
          command: |
            npm run build --prefix client

  test-server:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Install Server Dependencies"
          command: |
            npm install --prefix server
      - run:
          name: "Run Server Tests"
          command: |
            npm test --prefix server

  test-client:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Install Client Dependencies"
          command: |
            npm install --prefix client
      - run:
          name: "Run Client Tests"
          command: |
            npm test --prefix client

  sonarqube_scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: "Run SonarQube Scan for Server"
          command: |
            cd server && sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url="$SONAR_HOST_URL" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.sources="." \
              -Dsonar.branch.name="${CIRCLE_BRANCH}" \
              -Dsonar.exclusions="**/*.c,**/*.cpp,**/*.h,**/tests/**" \
              -Dsonar.c.file.suffixes=- \
              -Dsonar.cpp.file.suffixes=- \
              -Dsonar.objc.file.suffixes=-
      - run:
          name: "Run SonarQube Scan for Client"
          command: |
            cd client && sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url="$SONAR_HOST_URL" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.sources="." \
              -Dsonar.branch.name="${CIRCLE_BRANCH}" \
              -Dsonar.exclusions="**/*.c,**/*.cpp,**/*.h,**/tests/**" \
              -Dsonar.c.file.suffixes=- \
              -Dsonar.cpp.file.suffixes=- \
              -Dsonar.objc.file.suffixes=-

workflows:
  version: 2
  devsecops_pipeline:
    jobs:
      - build-server
      - build-client
      - test-server:
          requires:
            - build-server
      - test-client:
          requires:
            - build-client
      - sonarqube_scan:
          requires:
            - test-server
            - test-client
          filters:
            branches:
              only:
                - main
